- name: create iam roles for cluster {{ clusterSpec.cluster_name }}
  iam_role:
    name: '{{ item.key }}-{{ clusterSpec.cluster_name }}'
    managed_policy: '{{ item.value.policies }}'
    state: "present"
    create_instance_profile: no
    description: '{{ item.key }}-{{ clusterSpec.cluster_name }}'
    assume_role_policy_document: |
      {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            },
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::{{ account_number }}:role/nodes.{{ clusterSpec.cluster_name}}"
              },
              "Action": "sts:AssumeRole"
            },
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::{{ account_number }}:role/masters.{{ clusterSpec.cluster_name }}"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
  with_dict: '{{ iam_roles }}'

